name: Deploy React Frontpage to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug workspace
        run: |
          echo "WORKSPACE: $GITHUB_WORKSPACE"
          pwd
          ls -R .

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build
        # -> outputs into build/ per your vite.config.js

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Ensure target dir exists
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} \
            "mkdir -p /home/ubuntu/react/frontpage"

      - name: Copy built files to server
        run: |
          scp -r build/* \
            ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/react/frontpage/
